---
resource_types:
- name: concourse-pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource

resources:
- name: my-pipelines
  type: concourse-pipeline
  source:    
    target: http://concourse_web:8080
    insecure: "true"
    teams:
    - name: main
      username: test
      password: test    


- name: github
  type: git
  source:
    uri: http://172.16.197.129:7990/scm/tmq/maaah-code.git
    username: jjghali
    password: 6tfc7ygv

- name: cmbranch-git
  type: git
  source:
    uri: https://github.com/jjghali/concourse-multibranch.git
    username: jjghali
    password: 76d09d8b28352cbf410f3c5359ce51ce173525b0
    branch: master

jobs:
- name: transformPipelines
  plan:
  - get: github
  - get: my-pipelines
  - get: cmbranch-git
    trigger: true
  - task: get-pipelines
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: node, tag: "10" }
      inputs:
        - name: github
        - name: my-pipelines
        - name: cmbranch-git
      outputs:
      - name: generated-pipelines
      run:
        path: /bin/sh
        args:
          - -c
          - |
            # mkdir generated-pipelines
            cd cmbranch-git
            npm install
            npm run build
            cd ..
            # node cmbranch-git/dist/index.js ba --git-url http://172.16.197.129:7990 -P tmq -r maaah-code -u jjghali -p 6tfc7ygv 
            node cmbranch-git/dist/index.js gp --git-url http://172.16.197.129:7990 -j template -i my-pipelines/main-TemplatePipeline.yml -P tmq -r maaah-code -u jjghali -p 6tfc7ygv -O > output.pipeline.yml 
            mv output.pipeline.yml generated-pipelines
      
  - put: my-pipelines
    params:
      pipelines:
        - name: TemplatePipeline
          team: main
          config_file: generated-pipelines/output.pipeline.yml

