---
resources:
- name: github
  type: git
  source:
    uri: http://172.16.197.129:7990/scm/tmq/maaah-code.git
    username: jjghali
    password: 6tfc7ygv

jobs:
- name: template
  plan:
  - get: github
    trigger: true
  - task: listFiles 
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: ubuntu, tag: "bionic" }
      inputs:
        - name: github        
      run:
        path: /bin/sh
        args:
          - -c
          - |            
            ls -al github