version: '3.3'

services: 
    concourse-multibranch:
        build: 
            context: .
            dockerfile: Dockerfile
        
        environment:
            cmbCommand: gp --help           
                